##
## - collada_joint_name : euslisp_joint_name (start with :)
##

torso:
  - CHEST_JOINT0    : torso-waist-y
rarm:
  - RARM_JOINT0     : rarm-shoulder-y
  - RARM_JOINT1     : rarm-shoulder-p
  - RARM_JOINT2     : rarm-shoulder-r
  - RARM_JOINT3     : rarm-elbow-p
  - RARM_JOINT4     : rarm-elbow-r
  - RARM_JOINT5     : rarm-wrist-p
larm:
  - LARM_JOINT0     : larm-shoulder-y
  - LARM_JOINT1     : larm-shoulder-p
  - LARM_JOINT2     : larm-shoulder-r
  - LARM_JOINT3     : larm-elbow-p
  - LARM_JOINT4     : larm-elbow-r
  - LARM_JOINT5     : larm-wrist-p
head:
  - HEAD_JOINT0     : head-neck-y
  - HEAD_JOINT1     : head-neck-p

angle-vector:
  reset-pose : [0, -0.6, 0, -100, 15.2, 9.4, 3.2, .6, 0, -100, -15.2, 9.4, -3.2, 0, 0]

rarm-end-coords:
  parent : RARM_JOINT5_Link
  translate : [-0.19, 0, 0]
  rotate : [0, 1, 0, 90]
larm-end-coords:
  parent : LARM_JOINT5_Link
  translate : [-0.19, 0, 0]
  rotate : [0, 1, 0, 90]
head-end-coords:
  translate : [0.06, 0, 0.025]
  rotate : [0, 1, 0, 90]
